services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    directory: backend  # This tells Render to use the backend folder
